"""
XenoSys Core - Memory System (L1/L2/L3)
Three-tier hierarchical memory architecture
"""

from __future__ import annotations

import asyncio
import logging
import time
from abc import ABC, abstractmethod
from collections import OrderedDict
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, AsyncGenerator
from uuid import uuid4

import networkx as nx

logger = logging.getLogger(__name__)


# ============================================================================
# Memory Types
# ============================================================================

@dataclass
class MemoryEntry:
    """A single memory entry."""
    id: str = field(default_factory=lambda: str(uuid4()))
    content: str = ""
    embedding: list[float] | None = None  # For L2 semantic search
    
    # Metadata
    created_at: datetime = field(default_factory=datetime.utcnow)
    accessed_at: datetime = field(default_factory=datetime.utcnow)
    access_count: int = 0
    
    # Classification
    namespace: str = "default"
    importance: float = 1.0  # 0-1
    category: str = "general"
    
    # Relationships
    tags: list[str] = field(default_factory=list)
    links: list[str] = field(default_factory=list)  # IDs of related entries
    
    # Source tracking
    session_id: str | None = None
    user_id: str | None = None
    agent_id: str | None = None
    
    # TTL (for L1)
    expires_at: datetime | None = None
    
    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "id": self.id,
            "content": self.content,
            "created_at": self.created_at.isoformat(),
            "accessed_at": self.accessed_at.isoformat(),
            "access_count": self.access_count,
            "namespace": self.namespace,
            "importance": self.importance,
            "category": self.category,
            "tags": self.tags,
            "links": self.links,
            "session_id": self.session_id,
            "user_id": self.user_id,
            "agent_id": self.agent_id,
        }
    
    @property
    def is_expired(self) -> bool:
        """Check if entry has expired."""
        if self.expires_at is None:
            return False
        return datetime.utcnow() > self.expires_at


@dataclass
class SearchResult:
    """Result from memory search."""
    entry: MemoryEntry
    score: float = 0.0
    rank: int = 0


@dataclass
class Episode:
    """An episodic memory (conversation session)."""
    id: str = field(default_factory=lambda: str(uuid4()))
    session_id: str = ""
    user_id: str = ""
    
    # Messages
    messages: list[dict[str, Any]] = field(default_factory=list)
    
    # Timestamps
    started_at: datetime = field(default_factory=datetime.utcnow)
    ended_at: datetime | None = None
    duration_seconds: float = 0.0
    
    # Summary (generated by LLM)
    summary: str = ""
    topics: list[str] = field(default_factory=list)
    sentiment: str = "neutral"
    
    # Metrics
    message_count: int = 0
    token_count: int = 0
    
    # Outcome
    outcome: str | None = None
    satisfaction: float | None = None
    
    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "id": self.id,
            "session_id": self.session_id,
            "user_id": self.user_id,
            "started_at": self.started_at.isoformat(),
            "ended_at": self.ended_at.isoformat() if self.ended_at else None,
            "duration_seconds": self.duration_seconds,
            "summary": self.summary,
            "topics": self.topics,
            "sentiment": self.sentiment,
            "message_count": self.message_count,
            "token_count": self.token_count,
            "outcome": self.outcome,
            "satisfaction": self.satisfaction,
        }


# ============================================================================
# Memory Layer Base
# ============================================================================

class MemoryLayer(ABC):
    """Base class for memory layers."""
    
    @abstractmethod
    async def write(self, entry: MemoryEntry) -> str:
        """Write a memory entry. Returns entry ID."""
        pass
    
    @abstractmethod
    async def read(self, entry_id: str) -> MemoryEntry | None:
        """Read a memory entry by ID."""
        pass
    
    @abstractmethod
    async def search(
        self,
        query: str,
        namespace: str = "default",
        limit: int = 10,
        **kwargs: Any,
    ) -> list[SearchResult]:
        """Search memory entries."""
        pass
    
    @abstractmethod
    async def delete(self, entry_id: str) -> bool:
        """Delete a memory entry."""
        pass
    
    @abstractmethod
    async def clear(self, namespace: str | None = None) -> int:
        """Clear memory entries."""
        pass
    
    @abstractmethod
    async def stats(self) -> dict[str, Any]:
        """Get memory statistics."""
        pass


# ============================================================================
# L1 Memory - Working Context
# ============================================================================

class L1Memory(MemoryLayer):
    """
    L1 Working Context Memory
    
    - Ultra-fast, in-memory cache
    - LRU eviction policy
    - TTL-based expiration
    - Recent conversation context
    - Current task state
    
    Optimized for <10ms access latency.
    """
    
    def __init__(
        self,
        max_size: int = 10000,
        default_ttl_seconds: int = 3600,
        importance_threshold: float = 0.5,
    ) -> None:
        self.max_size = max_size
        self.default_ttl_seconds = default_ttl_seconds
        self.importance_threshold = importance_threshold
        
        # LRU cache
        self._cache: OrderedDict[str, MemoryEntry] = OrderedDict()
        self._lock = asyncio.Lock()
        
        # Statistics
        self._hits = 0
        self._misses = 0
    
    async def write(self, entry: MemoryEntry) -> str:
        """Write to L1 cache."""
        async with self._lock:
            # Set expiration
            if entry.expires_at is None:
                from datetime import timedelta
                entry.expires_at = datetime.utcnow() + timedelta(seconds=self.default_ttl_seconds)
            
            # Check size and evict if needed
            while len(self._cache) >= self.max_size:
                self._evict_lru()
            
            # Store
            self._cache[entry.id] = entry
            self._cache.move_to_end(entry.id)
            
            return entry.id
    
    async def read(self, entry_id: str) -> MemoryEntry | None:
        """Read from L1 cache."""
        async with self._lock:
            entry = self._cache.get(entry_id)
            
            if entry is None:
                self._misses += 1
                return None
            
            # Check expiration
            if entry.is_expired:
                del self._cache[entry_id]
                self._misses += 1
                return None
            
            # Update access
            entry.accessed_at = datetime.utcnow()
            entry.access_count += 1
            self._cache.move_to_end(entry_id)
            self._hits += 1
            
            return entry
    
    async def search(
        self,
        query: str,
        namespace: str = "default",
        limit: int = 10,
        **kwargs: Any,
    ) -> list[SearchResult]:
        """
        Search L1 memory.
        
        For L1, we do simple text matching since we don't have embeddings.
        In production, this would use a fast embedding index.
        """
        results: list[tuple[MemoryEntry, float]] = []
        
        async with self._lock:
            query_lower = query.lower()
            
            for entry in self._cache.values():
                if entry.namespace != namespace:
                    continue
                if entry.is_expired:
                    continue
                
                # Simple relevance scoring
                content_lower = entry.content.lower()
                
                if query_lower in content_lower:
                    # Exact match
                    score = 1.0
                else:
                    # Partial match based on words
                    query_words = set(query_lower.split())
                    content_words = set(content_lower.split())
                    overlap = len(query_words & content_words)
                    score = overlap / max(len(query_words), 1)
                
                if score > 0:
                    results.append((entry, score))
        
        # Sort by score and importance
        results.sort(key=lambda x: -(x[1] * x[0].importance))
        
        return [
            SearchResult(entry=e, score=s, rank=i)
            for i, (e, s) in enumerate(results[:limit])
        ]
    
    async def delete(self, entry_id: str) -> bool:
        """Delete from L1 cache."""
        async with self._lock:
            if entry_id in self._cache:
                del self._cache[entry_id]
                return True
            return False
    
    async def clear(self, namespace: str | None = None) -> int:
        """Clear L1 cache."""
        async with self._lock:
            if namespace is None:
                count = len(self._cache)
                self._cache.clear()
                return count
            
            # Clear by namespace
            to_delete = [
                eid for eid, e in self._cache.items()
                if e.namespace == namespace
            ]
            for eid in to_delete:
                del self._cache[eid]
            return len(to_delete)
    
    async def stats(self) -> dict[str, Any]:
        """Get L1 statistics."""
        async with self._lock:
            total = self._hits + self._misses
            hit_rate = self._hits / total if total > 0 else 0.0
            
            return {
                "layer": "L1",
                "size": len(self._cache),
                "max_size": self.max_size,
                "hits": self._hits,
                "misses": self._misses,
                "hit_rate": hit_rate,
                "utilization": len(self._cache) / self.max_size if self.max_size > 0 else 0,
            }
    
    def _evict_lru(self) -> None:
        """Evict least recently used entry."""
        if self._cache:
            self._cache.popitem(last=False)
    
    async def get_recent(
        self,
        namespace: str = "default",
        limit: int = 10,
    ) -> list[MemoryEntry]:
        """Get most recent entries."""
        async with self._lock:
            entries = [
                e for e in self._cache.values()
                if e.namespace == namespace and not e.is_expired
            ]
            entries.sort(key=lambda e: -e.accessed_at.timestamp())
            return entries[:limit]
    
    async def get_context(
        self,
        session_id: str,
        user_id: str | None = None,
        limit: int = 20,
    ) -> list[MemoryEntry]:
        """Get recent context for a session."""
        async with self._lock:
            entries = [
                e for e in self._cache.values()
                if e.session_id == session_id and not e.is_expired
                and (user_id is None or e.user_id == user_id)
            ]
            entries.sort(key=lambda e: -e.created_at.timestamp())
            return entries[:limit]


# ============================================================================
# L2 Memory - Semantic Store
# ============================================================================

class L2Memory(MemoryLayer):
    """
    L2 Semantic Memory
    
    - Vector embeddings for semantic search
    - ChromaDB-backed persistent storage
    - Cross-session knowledge retention
    - Importance-weighted retrieval
    
    Optimized for <100ms search latency.
    """
    
    def __init__(
        self,
        persist_directory: str = "./data/l2_memory",
        collection_name: str = "semantic",
        embedding_model: str = "sentence-transformers/all-MiniLM-L6-v2",
        top_k: int = 5,
    ) -> None:
        self.persist_directory = persist_directory
        self.collection_name = collection_name
        self.embedding_model = embedding_model
        self.top_k = top_k
        
        # ChromaDB client (lazy initialization)
        self._client = None
        self._collection = None
        self._embedder = None
        
        # Sync queue for L1-L2 transfer
        self._sync_queue: asyncio.Queue[MemoryEntry] = asyncio.Queue(maxsize=1000)
        self._sync_task: asyncio.Task[None] | None = None
    
    async def initialize(self) -> None:
        """Initialize L2 memory."""
        try:
            import chromadb
            from chromadb.config import Settings
            from sentence_transformers import SentenceTransformer
            
            # Initialize ChromaDB
            self._client = chromadb.PersistentClient(
                path=self.persist_directory,
                settings=Settings(anonymized_telemetry=False),
            )
            
            self._collection = self._client.get_or_create_collection(
                name=self.collection_name,
                metadata={"description": "XenoSys L2 Semantic Memory"},
            )
            
            # Initialize embedder
            self._embedder = SentenceTransformer(self.embedding_model)
            
            # Start sync task
            self._sync_task = asyncio.create_task(self._sync_loop())
            
            logger.info(f"L2 memory initialized: {self.persist_directory}")
            
        except ImportError as e:
            logger.warning(f"L2 dependencies not available: {e}")
            # Graceful degradation
    
    async def write(self, entry: MemoryEntry) -> str:
        """Write to L2 with embedding."""
        if self._collection is None or self._embedder is None:
            raise RuntimeError("L2 memory not initialized")
        
        # Generate embedding
        embedding = self._embedder.encode(entry.content).tolist()
        entry.embedding = embedding
        
        # Store in ChromaDB
        self._collection.add(
            ids=[entry.id],
            embeddings=[embedding],
            documents=[entry.content],
            metadatas=[{
                "namespace": entry.namespace,
                "importance": entry.importance,
                "category": entry.category,
                "tags": ",".join(entry.tags),
                "created_at": entry.created_at.isoformat(),
                "session_id": entry.session_id or "",
                "user_id": entry.user_id or "",
                "agent_id": entry.agent_id or "",
            }],
        )
        
        return entry.id
    
    async def read(self, entry_id: str) -> MemoryEntry | None:
        """Read from L2."""
        if self._collection is None:
            return None
        
        result = self._collection.get(ids=[entry_id])
        
        if not result["ids"]:
            return None
        
        return self._result_to_entry(result, 0)
    
    async def search(
        self,
        query: str,
        namespace: str = "default",
        limit: int = 10,
        importance_weight: float = 0.3,
        **kwargs: Any,
    ) -> list[SearchResult]:
        """Semantic search in L2."""
        if self._collection is None or self._embedder is None:
            return []
        
        # Embed query
        query_embedding = self._embedder.encode(query).tolist()
        
        # Search ChromaDB
        where_filter = {"namespace": namespace} if namespace != "default" else None
        
        results = self._collection.query(
            query_embeddings=[query_embedding],
            n_results=limit * 2,  # Overfetch for filtering
            where=where_filter,
        )
        
        if not results["ids"] or not results["ids"][0]:
            return []
        
        # Parse results
        search_results: list[SearchResult] = []
        for i, (entry_id, distance) in enumerate(zip(
            results["ids"][0],
            results["distances"][0],
        )):
            entry = await self.read(entry_id)
            if entry:
                # Convert distance to similarity score (0-1, higher is better)
                score = 1.0 / (1.0 + distance)
                # Blend with importance
                final_score = (1 - importance_weight) * score + importance_weight * entry.importance
                
                search_results.append(SearchResult(
                    entry=entry,
                    score=final_score,
                    rank=i,
                ))
        
        # Sort by final score
        search_results.sort(key=lambda x: -x.score)
        
        return search_results[:limit]
    
    async def delete(self, entry_id: str) -> bool:
        """Delete from L2."""
        if self._collection is None:
            return False
        
        try:
            self._collection.delete(ids=[entry_id])
            return True
        except Exception:
            return False
    
    async def clear(self, namespace: str | None = None) -> int:
        """Clear L2 collection."""
        if self._collection is None:
            return 0
        
        if namespace:
            self._collection.delete(where={"namespace": namespace})
            return 1
        
        self._collection.delete()
        return 1
    
    async def stats(self) -> dict[str, Any]:
        """Get L2 statistics."""
        if self._collection is None:
            return {"layer": "L2", "status": "not_initialized"}
        
        return {
            "layer": "L2",
            "count": self._collection.count(),
            "persist_directory": self.persist_directory,
            "embedding_model": self.embedding_model,
        }
    
    def _result_to_entry(self, result: dict, index: int) -> MemoryEntry:
        """Convert ChromaDB result to MemoryEntry."""
        meta = result["metadatas"][0][index] if result["metadatas"] else {}
        
        return MemoryEntry(
            id=result["ids"][0][index],
            content=result["documents"][0][index] if result["documents"] else "",
            namespace=meta.get("namespace", "default"),
            importance=float(meta.get("importance", 1.0)),
            category=meta.get("category", "general"),
            tags=meta.get("tags", "").split(",") if meta.get("tags") else [],
            session_id=meta.get("session_id") or None,
            user_id=meta.get("user_id") or None,
            agent_id=meta.get("agent_id") or None,
        )
    
    async def _sync_loop(self) -> None:
        """Background sync from L1 to L2."""
        while True:
            try:
                entry = await asyncio.wait_for(
                    self._sync_queue.get(),
                    timeout=5.0,
                )
                
                # Only sync important entries
                if entry.importance >= self.importance_threshold:
                    await self.write(entry)
                    
            except asyncio.TimeoutError:
                continue
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"L2 sync error: {e}")
    
    async def queue_sync(self, entry: MemoryEntry) -> None:
        """Queue entry for L1-L2 sync."""
        await self._sync_queue.put(entry)


# ============================================================================
# L3 Memory - Episodic & Long-term
# ============================================================================

class L3Memory(MemoryLayer):
    """
    L3 Episodic & Long-term Memory
    
    - PostgreSQL-backed persistent storage
    - Conversation episode tracking
    - User preference learning
    - Cross-agent knowledge sharing
    
    Optimized for complex queries and aggregations.
    """
    
    def __init__(
        self,
        connection_string: str = "postgresql://localhost/xenosys",
        pool_size: int = 10,
        max_overflow: int = 20,
    ) -> None:
        self.connection_string = connection_string
        self.pool_size = pool_size
        self.max_overflow = max_overflow
        
        self._engine = None
        self._session_factory = None
    
    async def initialize(self) -> None:
        """Initialize L3 database."""
        try:
            from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
            from sqlalchemy.orm import sessionmaker
            from sqlalchemy import Column, String, Text, Float, Integer, DateTime, JSON
            from sqlalchemy.ext.declarative import declarative_base
            
            Base = declarative_base()
            
            # Define tables
            class MemoryRecord(Base):
                __tablename__ = "memories"
                
                id = Column(String, primary_key=True)
                content = Column(Text, nullable=False)
                embedding = Column(JSON)  # Store as JSON for compatibility
                namespace = Column(String, default="default")
                importance = Column(Float, default=1.0)
                category = Column(String, default="general")
                tags = Column(JSON)
                links = Column(JSON)
                session_id = Column(String)
                user_id = Column(String)
                agent_id = Column(String)
                created_at = Column(DateTime, default=datetime.utcnow)
                accessed_at = Column(DateTime, default=datetime.utcnow)
                access_count = Column(Integer, default=0)
            
            class EpisodeRecord(Base):
                __tablename__ = "episodes"
                
                id = Column(String, primary_key=True)
                session_id = Column(String, index=True)
                user_id = Column(String, index=True)
                started_at = Column(DateTime, default=datetime.utcnow)
                ended_at = Column(DateTime)
                duration_seconds = Column(Float, default=0)
                summary = Column(Text)
                topics = Column(JSON)
                sentiment = Column(String, default="neutral")
                message_count = Column(Integer, default=0)
                token_count = Column(Integer, default=0)
                outcome = Column(Text)
                satisfaction = Column(Float)
            
            # Create engine
            self._engine = create_async_engine(
                connection_string,
                pool_size=self.pool_size,
                max_overflow=self.max_overflow,
                echo=False,
            )
            
            # Create tables
            async with self._engine.begin() as conn:
                await conn.run_sync(Base.metadata.create_all)
            
            # Session factory
            async_session = sessionmaker(
                self._engine, class_=AsyncSession, expire_on_commit=False
            )
            self._session_factory = async_session
            
            # Store table classes for queries
            self._MemoryRecord = MemoryRecord
            self._EpisodeRecord = EpisodeRecord
            
            logger.info("L3 memory initialized")
            
        except ImportError as e:
            logger.warning(f"L3 dependencies not available: {e}")
    
    async def write(self, entry: MemoryEntry) -> str:
        """Write to L3."""
        if self._session_factory is None:
            raise RuntimeError("L3 memory not initialized")
        
        async with self._session_factory() as session:
            from sqlalchemy import insert
            
            record = {
                "id": entry.id,
                "content": entry.content,
                "embedding": entry.embedding,
                "namespace": entry.namespace,
                "importance": entry.importance,
                "category": entry.category,
                "tags": entry.tags,
                "links": entry.links,
                "session_id": entry.session_id,
                "user_id": entry.user_id,
                "agent_id": entry.agent_id,
            }
            
            await session.execute(
                insert(self._MemoryRecord).values(**record)
            )
            await session.commit()
            
        return entry.id
    
    async def read(self, entry_id: str) -> MemoryEntry | None:
        """Read from L3."""
        if self._session_factory is None:
            return None
        
        async with self._session_factory() as session:
            from sqlalchemy import select
            
            result = await session.execute(
                select(self._MemoryRecord).where(
                    self._MemoryRecord.id == entry_id
                )
            )
            record = result.scalar_one_or_none()
            
            if not record:
                return None
            
            return MemoryEntry(
                id=record.id,
                content=record.content,
                embedding=record.embedding,
                namespace=record.namespace,
                importance=record.importance,
                category=record.category,
                tags=record.tags or [],
                links=record.links or [],
                session_id=record.session_id,
                user_id=record.user_id,
                agent_id=record.agent_id,
            )
    
    async def search(
        self,
        query: str,
        namespace: str = "default",
        limit: int = 10,
        **kwargs: Any,
    ) -> list[SearchResult]:
        """
        Search L3.
        
        For L3, we primarily search by metadata since we may not have embeddings.
        Full semantic search would require pgvector extension.
        """
        if self._session_factory is None:
            return []
        
        async with self._session_factory() as session:
            from sqlalchemy import select, func
            
            # Text search using ILIKE
            stmt = select(self._MemoryRecord).where(
                self._MemoryRecord.namespace == namespace,
                self._MemoryRecord.content.ilike(f"%{query}%"),
            ).order_by(
                self._MemoryRecord.importance.desc(),
                self._MemoryRecord.accessed_at.desc(),
            ).limit(limit)
            
            result = await session.execute(stmt)
            records = result.scalars().all()
            
            return [
                SearchResult(
                    entry=MemoryEntry(
                        id=r.id,
                        content=r.content,
                        namespace=r.namespace,
                        importance=r.importance,
                        category=r.category,
                        tags=r.tags or [],
                        session_id=r.session_id,
                        user_id=r.user_id,
                    ),
                    score=r.importance,
                    rank=i,
                )
                for i, r in enumerate(records)
            ]
    
    async def delete(self, entry_id: str) -> bool:
        """Delete from L3."""
        if self._session_factory is None:
            return False
        
        async with self._session_factory() as session:
            from sqlalchemy import delete
            
            result = await session.execute(
                delete(self._MemoryRecord).where(
                    self._MemoryRecord.id == entry_id
                )
            )
            await session.commit()
            
            return result.rowcount > 0
    
    async def clear(self, namespace: str | None = None) -> int:
        """Clear L3."""
        if self._session_factory is None:
            return 0
        
        async with self._session_factory() as session:
            from sqlalchemy import delete
            
            if namespace:
                result = await session.execute(
                    delete(self._MemoryRecord).where(
                        self._MemoryRecord.namespace == namespace
                    )
                )
            else:
                result = await session.execute(
                    delete(self._MemoryRecord)
                )
            
            await session.commit()
            
            return result.rowcount
    
    async def stats(self) -> dict[str, Any]:
        """Get L3 statistics."""
        if self._session_factory is None:
            return {"layer": "L3", "status": "not_initialized"}
        
        async with self._session_factory() as session:
            from sqlalchemy import select, func
            
            count_result = await session.execute(
                select(func.count()).select_from(self._MemoryRecord)
            )
            memory_count = count_result.scalar()
            
            episode_result = await session.execute(
                select(func.count()).select_from(self._EpisodeRecord)
            )
            episode_count = episode_result.scalar()
            
            return {
                "layer": "L3",
                "memory_count": memory_count,
                "episode_count": episode_count,
            }
    
    # Episode management
    async def create_episode(self, episode: Episode) -> str:
        """Create a new episode."""
        if self._session_factory is None:
            raise RuntimeError("L3 memory not initialized")
        
        async with self._session_factory() as session:
            from sqlalchemy import insert
            
            await session.execute(
                insert(self._EpisodeRecord).values(
                    id=episode.id,
                    session_id=episode.session_id,
                    user_id=episode.user_id,
                    started_at=episode.started_at,
                    summary=episode.summary,
                    topics=episode.topics,
                    message_count=episode.message_count,
                )
            )
            await session.commit()
        
        return episode.id
    
    async def update_episode(self, episode: Episode) -> bool:
        """Update an episode."""
        if self._session_factory is None:
            return False
        
        async with self._session_factory() as session:
            from sqlalchemy import update
            
            result = await session.execute(
                update(self._EpisodeRecord).where(
                    self._EpisodeRecord.id == episode.id
                ).values(
                    ended_at=episode.ended_at,
                    duration_seconds=episode.duration_seconds,
                    summary=episode.summary,
                    topics=episode.topics,
                    sentiment=episode.sentiment,
                    message_count=episode.message_count,
                    token_count=episode.token_count,
                    outcome=episode.outcome,
                    satisfaction=episode.satisfaction,
                )
            )
            await session.commit()
            
            return result.rowcount > 0
    
    async def get_episodes(
        self,
        user_id: str | None = None,
        session_id: str | None = None,
        limit: int = 10,
    ) -> list[Episode]:
        """Get episodes with filters."""
        if self._session_factory is None:
            return []
        
        async with self._session_factory() as session:
            from sqlalchemy import select
            
            stmt = select(self._EpisodeRecord)
            
            if user_id:
                stmt = stmt.where(self._EpisodeRecord.user_id == user_id)
            if session_id:
                stmt = stmt.where(self._EpisodeRecord.session_id == session_id)
            
            stmt = stmt.order_by(self._EpisodeRecord.started_at.desc()).limit(limit)
            
            result = await session.execute(stmt)
            records = result.scalars().all()
            
            return [
                Episode(
                    id=r.id,
                    session_id=r.session_id,
                    user_id=r.user_id,
                    started_at=r.started_at,
                    ended_at=r.ended_at,
                    duration_seconds=r.duration_seconds,
                    summary=r.summary or "",
                    topics=r.topics or [],
                    sentiment=r.sentiment or "neutral",
                    message_count=r.message_count,
                    token_count=r.token_count,
                    outcome=r.outcome,
                    satisfaction=r.satisfaction,
                )
                for r in records
            ]


# ============================================================================
# Memory Manager
# ============================================================================

class MemoryManager:
    """
    Unified memory interface with L1/L2/L3 tiers.
    
    Handles:
    - Automatic tier routing
    - L1-L2-L3 sync
    - Importnce-based promotion
    - Query optimization
    """
    
    def __init__(
        self,
        l1_config: dict[str, Any] | None = None,
        l2_config: dict[str, Any] | None = None,
        l3_config: dict[str, Any] | None = None,
    ) -> None:
        self.l1 = L1Memory(**(l1_config or {}))
        self.l2 = L2Memory(**(l2_config or {}))
        self.l3 = L3Memory(**(l3_config or {}))
        
        self._importance_threshold = l1_config.get("importance_threshold", 0.7) if l1_config else 0.7
    
    async def initialize(self) -> None:
        """Initialize all memory layers."""
        await self.l2.initialize()
        await self.l3.initialize()
        logger.info("Memory manager initialized")
    
    async def write(
        self,
        content: str,
        namespace: str = "default",
        importance: float = 1.0,
        session_id: str | None = None,
        user_id: str | None = None,
        agent_id: str | None = None,
        tags: list[str] | None = None,
        category: str = "general",
    ) -> str:
        """
        Write to memory with automatic tier placement.
        
        High importance -> L1 + L2 + L3
        Medium importance -> L1 + L2 (async to L3)
        Low importance -> L1 only
        """
        entry = MemoryEntry(
            content=content,
            namespace=namespace,
            importance=importance,
            session_id=session_id,
            user_id=user_id,
            agent_id=agent_id,
            tags=tags or [],
            category=category,
        )
        
        # Always write to L1
        l1_id = await self.l1.write(entry)
        
        # L2 for important content
        if importance >= 0.5:
            try:
                await self.l2.write(entry)
            except Exception as e:
                logger.warning(f"L2 write failed: {e}")
        
        # L3 for very important content
        if importance >= self._importance_threshold:
            try:
                await self.l3.write(entry)
            except Exception as e:
                logger.warning(f"L3 write failed: {e}")
        
        return l1_id
    
    async def read(self, entry_id: str) -> MemoryEntry | None:
        """
        Read from memory, checking tiers in order.
        """
        # Try L1 first
        entry = await self.l1.read(entry_id)
        if entry:
            return entry
        
        # Try L2
        entry = await self.l2.read(entry_id)
        if entry:
            # Promote to L1
            await self.l1.write(entry)
            return entry
        
        # Try L3
        entry = await self.l3.read(entry_id)
        if entry:
            # Promote to L1 and L2
            await self.l1.write(entry)
            try:
                await self.l2.write(entry)
            except Exception:
                pass
            return entry
        
        return None
    
    async def search(
        self,
        query: str,
        namespace: str = "default",
        limit: int = 10,
        tiers: str = "all",  # "l1", "l2", "l3", "all"
    ) -> list[SearchResult]:
        """
        Search across memory tiers.
        
        Results are deduplicated and ranked by score.
        """
        all_results: dict[str, SearchResult] = {}
        
        search_tiers = []
        if tiers == "all" or tiers == "l1":
            search_tiers.append(self.l1)
        if tiers == "all" or tiers == "l2":
            search_tiers.append(self.l2)
        if tiers == "all" or tiers == "l3":
            search_tiers.append(self.l3)
        
        for tier in search_tiers:
            try:
                results = await tier.search(query, namespace, limit * 2)
                for r in results:
                    if r.entry.id not in all_results or r.score > all_results[r.entry.id].score:
                        all_results[r.entry.id] = r
            except Exception as e:
                logger.warning(f"{tier.__class__.__name__} search failed: {e}")
        
        # Sort and rank
        sorted_results = sorted(all_results.values(), key=lambda x: -x.score)
        for i, r in enumerate(sorted_results[:limit]):
            r.rank = i
        
        return sorted_results[:limit]
    
    async def get_context(
        self,
        session_id: str,
        user_id: str | None = None,
        limit: int = 20,
    ) -> list[MemoryEntry]:
        """Get recent context for a session."""
        return await self.l1.get_context(session_id, user_id, limit)
    
    async def stats(self) -> dict[str, Any]:
        """Get memory statistics for all tiers."""
        return {
            "l1": await self.l1.stats(),
            "l2": await self.l2.stats(),
            "l3": await self.l3.stats(),
        }